debug: true
server:
  port: 8085
spring:
  application:
    name: desafio-tecnico-previred-1
  datasource:
    password: ''
    url: jdbc:h2:mem:dbnuevospa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /auth/swagger-ui.html
