openapi: 3.0.1
info:
  title: OpenAPI desafio previred
  version: 1.0.0
servers:
  - url: http://localhost:8085
    description: Generated server url

paths:
  /authenticate/login:
    post:
      tags:
        - auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /updateTask/:
    post:
      tags:
        - task-controller
      operationId: updateTask
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Task'
  /api/tareas/save:
    post:
      tags:
        - task-controller
      operationId: saveTask
      requestBody:
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json;charset=utf-8:
              schema:
                $ref: '#/components/schemas/Task'
  /findById/{id}:
    get:
      tags:
        - task-controller
      operationId: findById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Task'
    /deleteTask/{id}:
      tags:
        - task-controller
      operationId: deleteTask
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /findAllTasks:
    get:
      tags:
        - task-controller
      operationId: findAllTasks
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
  
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        token:
          type: string
    TaskStatus:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descripcion:
          type: string
    GrantedAuthority:
      type: object
      properties:
        authority:
          type: string
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
        descripcion:
          type: string
        estadoTask:
          $ref: '#/components/schemas/TaskStatus'
        usuario:
          $ref: '#/components/schemas/Usuario'
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum:
            - ADMIN
            - USER
        enabled:
          type: boolean
        authorities:
          type: array
          items:
            $ref: '#/components/schemas/GrantedAuthority'
        accountNonLocked:
          type: boolean
        credentialsNonExpired:
          type: boolean
        accountNonExpired:
          type: boolean
